### ISSUE TITLE
please make checkboxes independent

### ISSUE THREAD

**Issue by MariMax** [Mariya-Z/next-three-state-checkbox#31]
https://epam-my.sharepoint.com/:v:/p/maxim_milovanov/ES8CGZhsiUlOt3-HVw2GV_ABb1nnd8ewNZIxRwEmv-FEMA?e=AC2gd9

https://epam-my.sharepoint.com/:v:/p/maxim_milovanov/EdUH_PXgB0FBm-Mqh5Gj-oABQbAtJpN7Z7K7fjQN6ABaFw?e=NM7KFI

**Comment by mariia-zu** [comment]
I can't watch these videos =(
![image](https://user-images.githubusercontent.com/35897561/54419811-64a80c00-4719-11e9-9f6f-ee618ebfe395.png)

**Comment by MariMax** [comment]
you can always download them and watch in some better player
